---
title: "Computational Lab Notebook"
subtitle: "AdEx implementation in NetPyNe"
author: "Javier Palma Espinosa"
date: '`r paste("Last Revision: ",Sys.Date())`'
header-includes:
  - \usepackage{pdfpages}
output:
  pdf_document:
    template: /home/javier/.pandoc/templates/eisvogel.latex
    toc: true
    number_sections: yes
    latex_engine: xelatex
  word_document:
    toc: yes
    toc_depth: '2'
  html_document: default
titlepage: true
#titlepage-background: /home/javier/Imágenes/bombus-transparency.jpg
titlepage-color: "2980b9"  #NetPyNe background color, color of lab notebooks
titlepage-text-color: "000000" 
titlepage-rule-color: "383E42" #Anthracite
titlepage-logo: /home/javier/Neuroscience/AdEx/docs/reports/figures/logo.png
titlepage-rule-height: 2
csl: ../references/frontiers-in-neuroscience.csl
bibliography: ../rmd/bib-proposal.bib  
biblio-style: "apalike"
link-citations: true
urlcolor: blue
linkcolor: blue
graphics: yes
---
```{r setup, include=TRUE, echo=FALSE}
library(reticulate)
library("ganttrify")
use_virtualenv("~/Environments/netpyne/")
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/information.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/changelog.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/workplan.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/Notes.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/Daily.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/preliminary-results.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/meetings.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/tips.rmd")}
```

\newpage

```{r child = here::here("AdEx/docs/reports/rmd/papers-analysis.rmd")}
```





\newpage

# References
