---
title: "Ph.D. Project Proposal"
author: "Javier Palma Espinosa"
date: '`r paste(Sys.Date())`'
output:
  pdf_document:
    template: /home/javier/.pandoc/templates/eisvogel.latex
    toc: true
titlepage: true
titlepage-background: /home/javier/Imágenes/fondoRmd.png
csl: ../references/nature-neuroscience.csl
bibliography: bib-proposal.bib  


---

# Attention
Attention is an essential neurobiological function that allows individuals to select the most important stimuli from its internal or external environment, for better allocation of neural resources to the processing of those stimuli. When two equally interesting stimuli are presented to the subject, it must be able to selectively redirect its own attention and focus on the most relevant stimuli for its own interest.  That process is framed as selective attention.



## Spiking Networks

## Insect as biological model

## Spiking networks and attention




While several mechanism and models have been proposed and studied to describe the selective attention phenomena, all of them have been proposed for mammals [@baghdadi2021neurocognitive].  Interestingly, the attentional function and selective attention in particular is not present only in mammals, but in insects as well [@nityananda2016attention].  For example, it has been shown that a simple "winner takes all" model in the visual structures of anisoptera is able to reproduce the selective attention phenomena. This simple response, triggers the coordination of eight motor neurons that finally allow the insect to capture its prey [@olberg2012visual;@wiederman2013selective]. However in himenoptera, the visual attentional circuitry is far more complex.  Studies have shown that multiple neuropils are involved in the visual attentional phenomena, namely optical lobes, central complex, and mushroom body [@paulk2008processing;@van2009shared;@grabowska2020oscillations;@paulk2014selective].

The way that these neuropils communicate themselves and process information is currently unknown. Previous studies of selective attention propose that oscillatory mechanisms are relevant in the representation of the relevant stimuli [@womelsdorf2007role]. Interestingly, the group of Van Swinderen showed that oscillatory activity is related with attentional tasks in the central complex and optical lobes in d. melanogaster [@grabowska2020oscillations;@paulk2014selective]. Additionally, olfactory attentional experiments have also shown oscillations in the mushroom body [@popov2020alpha]. 

Although the experimental paradigmn used by the group of Van Swinderen, based on steady-state visually evoked potential (SSVEP) may induce a missinterpretation of the attentional results, the experimental results in the olfactory system suggests that the oscillatory activity may indeed be a key mechanism for attentional process.  

Computational models of visual selective attention have shown that the oscillatory activity observed in the mushroom body may be enough to support the attentional selectivity [@arena2012modeling]. This is in line with a previous model proposed by Corchs & Deco [@corchs2001neurodynamical], which states that the oscillation is observed because a pool of simulataneous neuronal activity is synchonized, creating a diversity of dynamical states. While oscillation in neural structures seem to support attentional selectivity, in particular in the mushroom body, the key principles that sustain this function are not clear. 

One important characteristic of the mushroom body is its architecture. It has been framed as a feedforward network, where little to no modulatory activity is found, but it still is able to support associative learning [@aso2014neuronal]. However, the mushroom body structure contradicts with the literature, where small world or modular-like structure and not feed forward networks, supports the most rich patterns of activity in dynamical networks[@Palma-Espinosa2021Structure].  

In this work, I will implement a computational model of spiking neural network that will test different network architectures and measure its selectivity characteristics, oscillatory characteristics and encoding properties. The main objective is to answer the question: **is the architectural topology of the mushroom body is enough to support not only oscillatory activity, but also a way to selectively pick the most important features?**


# Methods

## Spiking Neural Network

## Adex Model

## Kenyon cell modeling


## LFP modeling and reconstruction

# Results

# Discussion

# References